// Module included in the following assemblies:
//
// * installing/installing_aws/installing-aws-government-region.adoc
// * installing/installing_aws/installing-aws-secret-region.adoc

ifeval::["{context}" == "installing-aws-government-region"]
:aws-gov:
endif::[]
ifeval::["{context}" == "installing-aws-secret-region"]
:aws-secret:
endif::[]

[id="installation-aws-about-gov-secret-region_{context}"]
ifdef::aws-gov[]
= AWS government regions
endif::aws-gov[]
ifdef::aws-secret[]
= AWS Top Secret Region
endif::aws-secret[]

ifdef::aws-gov[]
{product-title} supports deploying a cluster to an link:https://aws.amazon.com/govcloud-us[AWS GovCloud (US)] region.
endif::aws-gov[]

ifdef::aws-secret[]
{product-title} supports deploying a cluster to an link:https://aws.amazon.com/federal/us-intelligence-community/[AWS Commercial Cloud Services (C2S) Top Secret Region].
endif::aws-secret[]

ifdef::aws-secret[]
The C2S Top Secret Region does not have a published {op-system-first} Amazon Machine Images (AMI) to select, so you
must upload a custom AMI that belongs to that region.
endif::aws-secret[]

ifdef::aws-gov[]
The following AWS GovCloud partitions are supported:

* `us-gov-east-1`
* `us-gov-west-1`
endif::aws-gov[]

ifdef::aws-secret[]
The following AWS Top Secret Region partition is supported:

* `us-iso-east-1`
[NOTE]
====
The MTU of the AWS SDN in the us-iso-east-1 region is not the same as AWS commercial. For configuring the MTU during cluster install, see link:https://docs.openshift.com/container-platform/4.9/installing/installing_aws/installing-aws-network-customizations.html#nw-operator-cr-cno-object_installing-aws-network-customizations[Installing a cluster on AWS with network customizations].
====
endif::aws-secret[]

ifeval::["{context}" == "installing-aws-government-region"]
:!aws-gov:
endif::[]
ifeval::["{context}" == "installing-aws-secret-region"]
:!aws-secret:
endif::[]
